pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M2" and add it to the path.
        maven "M2"
    }

    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git credentialsId: 'GIT_CREDENTIALS', url: 'https://github.com/shankarvs84/spring-boot-sample'

                // Run Maven on a Unix agent.
                sh "mvn -Dmaven.test.failure.ignore=true clean install"

                // To run Maven on a Windows agent, use
                // bat "mvn -Dmaven.test.failure.ignore=true clean package"
            }

            post {
                // If Maven was able to run the tests, even if some of the test
                // failed, record the test results and archive the jar file.
                success {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'target/*.jar'
                    mail bcc: '', body: 'Maven build status for {env.BUILD_TAG}', cc: '', from: '', replyTo: '', subject: 'Maven build status for {env.BUILD_TAG}', to: 'shankarvs84@gmail.com'
                }
            }
        }
    }
}
